# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='derived_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Compound'),
        ),
    ]
