# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_auto_20160108_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cds',
            name='optimized_for',
            field=models.ForeignKey(help_text=b'Indicates the organism that the CDS was optimized for', null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Organism'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='target_part',
            field=models.ForeignKey(help_text=b'The Part that will be obtained with this oligo', null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.DNAPart'),
        ),
    ]
