# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 14:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0004_auto_20160108_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='oligo',
            name='sequence',
            field=models.CharField(default=0, help_text=b'A valid ATGC sequence', max_length=50000, validators=[django.core.validators.RegexValidator(b'^[CAGTcagt]+$', message=b'Not a valid DNA sequence.')], verbose_name='Type'),
            preserve_default=False,
        ),
    ]
