# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0005_oligo_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='results_summary',
            field=models.CharField(help_text=b'Quick summary of what was found in the assay.', max_length=1000000, verbose_name='Results summary'),
        ),
    ]
