# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 17:56
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0006_auto_20160120_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='content',
            field=tinymce.models.HTMLField(default=b''),
        ),
    ]
